[font]
size = 18.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[window]
dimensions = { columns = 100, lines = 25 }
decorations = "Full"
padding = { x = 8, y = 8 }

[general]
import = [
    "~/.config/alacritty/themes/themes/alabaster.toml"
]
